[package]
name = "bbpe"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.8.0"
# servo = { git = "https://github.com/BBaoVanC/servo", branch = "master" }
